---
- name: Add Helm repository
  ansible.builtin.command:
    cmd: helm repo add ingress-nginx https://kubernetes.github.io/ingress-nginx  --force-update
  args:
    creates: ~/.cache/helm/repository/ingress-nginx-index.yaml

- name: Install NGINX ingress using Helm
  ansible.builtin.command:
    cmd: >
      helm upgrade --install ingress-nginx ingress-nginx/ingress-nginx
      --namespace ingress-nginx
      --create-namespace
