---
- name: Add Helm repository
  ansible.builtin.command:
    cmd: helm repo add jetstack https://charts.jetstack.io --force-update
  args:
    creates: ~/.cache/helm/repository/cert-manager-index.yaml


- name: Install Cert-Manager using Helm
  ansible.builtin.command:
    cmd: >
      helm upgrade --install cert-manager jetstack/cert-manager
      --namespace cert-manager
      --create-namespace
      --version v1.16.2
      --set crds.enabled=true
      --set prometheus.enabled=false
      --set webhook.timeoutSeconds=4

# - name: Install cert-manger
#   kubernetes.core.k8s:
#     state: present
#     src: https://github.com/jetstack/cert-manager/releases/download/v1.7.1/cert-manager.yaml

# - name: Create ClusterIssuer
#   k8s:
#     state: present
#     definition:
#       apiVersion: cert-manager.io/v1
#       kind: ClusterIssuer
#       metadata:
#         name: "{{ cert_manager_issuer.name }}"
#         namespace: cert-manager
#       spec:
#         acme:
#           # The ACME server URL
#           server: "{{ cert_manager_issuer.server }}"
#           # Email address used for ACME registration
#           email: "{{ cert_manager_issuer.email }}"
#           # Name of a secret used to store the ACME account private key
#           privateKeySecretRef:
#             name: "{{ cert_manager_issuer.private_key_secret }}"
#           # Enable the HTTP-01 challenge provider
#           solvers:
#           - http01:
#               ingress:
#                 class:  nginx

# - name: Add cert-manager workaround
#   k8s:
#     state: present
#     definition:
#       apiVersion: v1
#       kind: Service
#       metadata:
#         annotations:
#           service.beta.kubernetes.io/do-loadbalancer-enable-proxy-protocol: 'true'
#           service.beta.kubernetes.io/do-loadbalancer-hostname: "workaround.nquirmbach.de"
#         labels:
#           helm.sh/chart: ingress-nginx-4.11.3
#           app.kubernetes.io/name: ingress-nginx
#           app.kubernetes.io/instance: ingress-nginx
#           app.kubernetes.io/version: 1.11.3
#           app.kubernetes.io/managed-by: Helm
#           app.kubernetes.io/component: controller
#         name: ingress-nginx-controller
#         namespace: ingress-nginx
#       spec:
#         type: LoadBalancer
#         externalTrafficPolicy: Local
#         ports:
#           - name: http
#             port: 80
#             protocol: TCP
#             targetPort: http
#           - name: https
#             port: 443
#             protocol: TCP
#             targetPort: https
#         selector:
#           app.kubernetes.io/name: ingress-nginx
#           app.kubernetes.io/instance: ingress-nginx
#           app.kubernetes.io/component: controller
