---

- name: Install cert-manger
  kubernetes.core.k8s:
    state: present
    src: https://github.com/jetstack/cert-manager/releases/download/v1.7.1/cert-manager.yaml

- name: Create ClusterIssuer
  k8s:
    state: present
    definition:
      apiVersion: cert-manager.io/v1
      kind: ClusterIssuer
      metadata:
        name: "{{ cert_manager_issuer.name }}"
        namespace: cert-manager
      spec:
      acme:
        # The ACME server URL
        server: "{{ cert_manager_issuer.server }}"
        # Email address used for ACME registration
        email: "{{ cert_manager_issuer.email }}"
        # Name of a secret used to store the ACME account private key
        privateKeySecretRef:
          name: "{{ cert_manager_issuer.private_key_secret }}"
        # Enable the HTTP-01 challenge provider
        solvers:
        - http01:
            ingress:
              class:  nginx
