name: Configure Kubernetes cluster
on:
  workflow_dispatch:
  push:
    branches:
      - staging
      - prod
    paths:
      - ansible/**
      - .github/workflows/configure-cluster.yml

jobs:
  configure-kubernetes:
    runs-on: ubuntu-latest
    environment: ${{ github.ref_name }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install Ansible
        run: |
          python -m pip install --upgrade pip
          pip install ansible openshift pyyaml kubernetes

      - name: Get kubeconfig
        run: doctl kubernetes cluster kubeconfig save ${{ vars.CLUSTER_NAME }}

      - name: Test connection
        run: kubectl get pods

      - name: Configure Kubernetes
        working-directory: ansible
        run: ansible-playbook k8s_setup.yaml -i inventories/${{ github.ref_name }}/hosts
